### PR TITLE
Add Lifka Shell

### PR DESCRIPTION
**Pull request by Lifka**

### CODE REVIEW

**Comment by JohnTroony** [comment]
Any details about the Add?

**Comment by Lifka** [comment]
I have added a new php webshell, this shell wasn't in the repository, only that. It is a webshell that I did some years ago.

**Comment by JohnTroony** [comment]
Okay, I'll have to test it and then merge the PR.

**Comment by JohnTroony** [comment]
Looks good... I'm merging
(I noticed, it's not fully in English but works fine and default password is `root`.)

**Comment by Lifka** [comment]
Thank you. It's true, the shell has some years, soon I will review and correct the language, I will probably make some improvement. I will do a commit when it happens.

**Pull request merged**
